# .github/workflows/ci.yml

name: Deploy Project Page

on:
  push:
    branches: [ "web-source" ] # 仅在推送到 web-source 分支时触发
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许一个并发部署，跳过排队的运行。
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          ref: 'web-source'

      - name: Set up Node.js 🟩
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: npm

      - name: Install dependencies 🔧
        run: npm install

      - name: Build 🏗️
        run: npm run build # 这会生成 dist 文件夹

      - name: Setup Pages ⚙️
        uses: actions/configure-pages@v4

      - name: Upload artifact 📦
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # 上传 dist 文件夹作为部署产物

      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4 # 部署之前上传的产物